Update update_image.yml

diff --git a/.github/workflows/update_image.yml b/.github/workflows/update_image.yml
--- a/.github/workflows/update_image.yml
+++ b/.github/workflows/update_image.yml
@@ -26,27 +26,37 @@ jobs:
       - name: Run Python Script
         run: python get_cotd.py  # Replace with your script filename
 
-      - name: Commit and Push Changes
-        run: |
-          git config --global user.name "GitHub Actions"
-          git config --global user.email "actions@github.com"
+
+      - uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: Automated Change
+          file_pattern: 'challenge_of_the_day/*.jpg'
+          commit_user_name: My GitHub Actions Bot
+          commit_user_email: my-github-actions-bot@example.org
+    
+
+
+      # - name: Commit and Push Changes
+      #   run: |
+      #     git config --global user.name "GitHub Actions"
+      #     git config --global user.email "actions@github.com"
           
-          # Fetch the latest changes from the remote branch
-          git fetch origin main
+      #     # Fetch the latest changes from the remote branch
+      #     git fetch origin main
 
-          # Attempt to merge the changes into the local branch
-          git merge origin/main || {
-            echo "Merge conflict or other issues, resetting to the remote branch."
-            git reset --hard origin/main
-          }
+      #     # Attempt to merge the changes into the local branch
+      #     git merge origin/main || {
+      #       echo "Merge conflict or other issues, resetting to the remote branch."
+      #       git reset --hard origin/main
+      #     }
 
-          # Add the new image and commit
-          git add challenge_of_the_day/
-          git commit -m "Auto-update image" || echo "No changes to commit"
+      #     # Add the new image and commit
+      #     git add challenge_of_the_day/
+      #     git commit -m "Auto-update image" || echo "No changes to commit"
 
-          # Push the changes
-          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/timonezitrone/testrepo.git || {
-            echo "Push failed, trying to pull and push again."
-            git pull origin main --rebase
-            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/timonezitrone/testrepo.git
-          }
+      #     # Push the changes
+      #     git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/timonezitrone/testrepo.git || {
+      #       echo "Push failed, trying to pull and push again."
+      #       git pull origin main --rebase
+      #       git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/timonezitrone/testrepo.git
+      #     }
